### ISSUE TITLE
Problem trying to include dependency to gradle

### ISSUE THREAD

**Issue by aderbas** [auth0/JWTDecode.Android#13]
I am trying to add in dependencies in my project but it is causing error. I know it's not a problem to be questioned here, but someone can help me. What happens is if I add:
`All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes).`
My gradle file:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "25.0.1"
    defaultConfig {
        applicationId "mobitrak.zenitetecnologia.com.br.mobitrak"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.auth0.android:jwtdecode:1.1.1'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha4'
    compile 'com.android.support:design:23.0.1'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.google.android.gms:play-services:10.0.1'
    compile 'com.google.firebase:firebase-messaging:9.6.1'
    compile 'com.android.support:multidex:1.0.1'

    testCompile 'junit:junit:4.12'
}

apply plugin: 'com.google.gms.google-services'

```

**Comment by lbalmaceda** [comment]
If you're still running into this issue, you can fix it by using the same `com.android.support` library versions as the ones [defined by this library](https://github.com/auth0/JWTDecode.Android/blob/master/lib/build.gradle#L44). They must all be the same, the ones from your app/lib and the ones from your dependency, or you'll run into this issue again. There's an alternative way to ignore these transitive dependencies with gradle, make sure to search that. 👍

**Comment by andre-artus** [comment]
I've included `implementation 'com.auth0.android:jwtdecode:2.0.0'` in the `dependencies` section of my `build.gradle` file but it does not recognize `com.auth0.android.jwt` in the imports. 

If I hover over `JWT("<token string>")` Android Studio shows "Add library 'Gradle: com.auth0.android:jwtdecode:2.0.0@aar' to classpath", but selecting that does nothing.

I have cleared my cache, made sure everything was synced, etc. but it still does not pick it up.

The files do, however, show up in my gradle cache:
```
...\com.auth0.android\jwtdecode\2.0.0\8b09625437690c1f873b52746cd4a1e983748683\jwtdecode-2.0.0.pom
...\com.auth0.android\jwtdecode\2.0.0\aa0edc4c18746a5775ef08e5edc6ffac5922c365\jwtdecode-2.0.0.aar
...\com.auth0.android\jwtdecode\2.0.0\dece19947db3f7b1b48ba3b49134e5cc2936a9bb\jwtdecode-2.0.0-sources.jar
...\com.auth0.android\jwtdecode\2.0.0\ed38fceb2c33b728fff18fa796ea446995a62551\jwtdecode-2.0.0-javadoc.jar
```

I'm using both  google() and mavenCentral() repositories (even added jcenter() just to see if it would make a difference) . Do I need to add the AAR manually?


I've never experienced this before.

**Comment by andre-artus** [comment]
Okay, it appears that the library I tried to call it from was a standard Java lib and not an AAR.

**Comment by lbalmaceda** [comment]
@andre-artus 👍  thanks for sharing your findings with us. If you are looking for a Java library for JWTs, we offer java-jwt instead. https://github.com/auth0/java-jwt/

**Comment by andre-artus** [comment]
> 
> 
> @andre-artus 👍 thanks for sharing your findings with us. If you are looking for a Java library for JWTs, we offer java-jwt instead. https://github.com/auth0/java-jwt/

Thanks
