### ISSUE TITLE
GSON unserialization issue

### ISSUE THREAD

**Issue by Llorc** [auth0/JWTDecode.Android#14]
Hello,

When I try 

`gson.fromJson(jsJWT, JWT.class) `

I get an exception: 

> java.lang.RuntimeException: Unable to invoke no-args constructor for interface com.auth0.android.jwt.Claim. Register an InstanceCreator with Gson for this type may fix this problem.

I use 'com.auth0.android:jwtdecode:1.1.1'

I hope you can help...
Thanks

**Comment by lbalmaceda** [comment]
If you're still running into this issue you're misusing the library. Tokens are meant to be translated from the "JWT string format" to a `JWT` instance, as shown by [this example](https://github.com/auth0/JWTDecode.Android#usage)
