### ISSUE TITLE
jwt.getExpiresAt().getTime() adds some zero that poison the exp field

### ISSUE THREAD

**Issue by Thecave3** [auth0/JWTDecode.Android#16]
I'm using your lib on my app and I was stuck until I found this bug because my server says that token has expired but inside the app the case of an expired token is prevented. 

So here is what happens all time: when I retrieve my jwt from the server I pass inside my shared preferences'handler the token as a string with this function:

```java    
private void setNewSession(String token, boolean firstLogin) {
        editor.putBoolean(IS_LOGIN, true);
        JWT jwt = new JWT(token);
        editor.putString(KEY_USER_TOKEN, token);
        editor.putLong(KEY_DEADLINE, jwt.getExpiresAt().getTime());
        editor.putBoolean(KEY_FIRST_LOGIN, firstLogin);
        editor.apply();
        if(DEBUG) {
            Log.d(TAG_USER_CLASS,"Token: "+ jwt);
            Log.d(TAG_USER_CLASS,"Data di scadenza del token in ms : "+ jwt.getExpiresAt().getTime());
            Log.d(TAG_USER_CLASS,"Data di scadenza del token: "+ DateFormat.getDateTimeInstance().format(jwt.getExpiresAt()));
        }
    }
```

The problem is with the method: `jwt.getExpiresAt().getTime()` because instaed of returning the correct time it returns the correct time as long + 000.
Here is an example of the token passed by the server and the return of the method:
![cattura](https://user-images.githubusercontent.com/14928080/35598637-ec2937f8-0624-11e8-91d1-c3a7fb41b093.JPG)

This is the result it should appear, I've calculated using the same token and the [jwt debugger on site](https://jwt.io/#libraries):

- token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1YTRmYTdlODUwNTdjNDU1NjRiZGIwNmMiLCJleHAiOjE1MTc0NDM3NDY4MzZ9.----OMITTEDKEYPART----

- "exp": 1517443746836

And as you can note that your library output (1517443746836000) is different from the site output (1517443746836).

Please let me know if you have the same issue that I have and hope you'll solve as soon as possible.

**Comment by anttisep** [comment]
The zeros are correct. `jwt.getExpiresAt()` return a java Date object. For Date, `getTime()` returns milliseconds from epoch which equals to the value of  jwt "exp" + "000". The "exp" is seconds from epoch.
https://docs.oracle.com/javase/7/docs/api/java/util/Date.html#getTime()

**Comment by Thecave3** [comment]
Ok, now I see the returns in milliseconds and not seconds, but I still not figure why this portion of code gave me 17 November 50055 as expire date. BTW now I can operate, thank you
