### ISSUE TITLE
Invalid JSON Format Exception

### ISSUE THREAD

**Issue by redbassett** [auth0/JWTDecode.Android#18]
I have an example JWT in this format:

> eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiZmIxNTQ5YmYtMWNmYi00ZjhiLTkxODgtZjZiMTgzYmVmOGFiIiwiZXhwIjoxNTIwNTUzMDQ5LCJpYXQiOiIyMDE4LTAyLTA4IDIzOjUwOjQ5IFVUQyJ9.EfkRQhLKelDXX6XPbA7wVug9k90wioHBhEc1vA07OAA

When I run this through `new JWT();`, I get an exception claiming some sort of invalid JSON formatting. I've looked at the Base64 decode of this string, and it looks valid too me, but the payload section is triggering an exception. What is wrong with this token? Is the lack of signature causing this issue?

**Comment by anttisep** [comment]
According to https://tools.ietf.org/html/rfc7519#section-4.1.6 registered claim "iat" should have a format of NumericDate, i.e. "Seconds Since the Epoch". Your example has:
"iat": "2018-02-08 23:50:49 UTC"
which is not a valid value for "iat".

**Comment by redbassett** [comment]
Good catch, thanks! My web team mostly uses that format, but I let them know they might want to look at that formatting.
