### ISSUE TITLE
Getting nested JSON from claim object.

### ISSUE THREAD

**Issue by rostyslavroshak** [auth0/JWTDecode.Android#21]
Current api allows only to get primitives from claim. In case claim contains objects they can't be parsed.

Since the library already uses GSON it would be very useful to parse the payload using it, instead of parsing it manually using `getBoolean`, `getInt` and so on methods.

**Comment by joshumax** [comment]
This was a major limiting factor for me as well.

Because the server issues nested JSON which I needed to parse I had to clone this into a local repository and modify it to add a `getSubElement()` claim method rather than just being able to use it through Maven...

**Comment by dustin-graham** [comment]
@joshumax this would be very useful, perhaps a pull request?

**Comment by LiYing2010** [comment]
Hi friends, I created a PR for this:
https://github.com/auth0/JWTDecode.Android/pull/25

Would you please take a look?

**Comment by lbalmaceda** [comment]
We don't plan to support this in the near future unless there's a specific Auth0 use case that is getting blocked because of this. We encourage to use plain and simple payloads instead of nesting all the possible information in a single token. I'll leave this open as a reminder to review this later and to give it more visibility.

**Comment by LiYing2010** [comment]
> We don't plan to support this in the near future unless there's a specific Auth0 use case that is getting blocked because of this.

Actually, we are developing an Auth0 flow, and kind of get blocked because of this.
We return an OpenID Token (in JWT format) as part of our auth result, and include an `address` claim in this token which represent the physical mailing address of user.
Accoding to the OpenID Connect spec, this `address` claim should be a JSON object, which contains sub-claims.

Please refer to: http://openid.net/specs/openid-connect-core-1_0.html#AddressClaim

That is why we need this `Getting nested JSON` feature.

Could you consider this use case, and kindly take a look at my PR?

**Comment by lucasantarella** [comment]
I second this. This would definitely be useful. Also, according to the JWT spec, this is definitely a valid implementation. See here:

> Both JWTs and SWTs [SWT], at their core, enable sets of claims to be
   communicated between applications.  For SWTs, both the claim names
   and claim values are strings.  For JWTs, while claim names are
   strings, claim values can be any JSON type.  - [RFC 7519](https://tools.ietf.org/html/rfc7519#page-29)

**Comment by cloudjubei** [comment]
@lbalmaceda and @hzalaz please check out @LiYing2010 pull request #25

**Comment by AHarazim** [comment]
Any news here? I'm also interested in this feature.

**Comment by chrisbtoo** [comment]
From https://tools.ietf.org/html/rfc7519#section-2:

>   Claim
>      A piece of information asserted about a subject.  A claim is
>      represented as a name/value pair consisting of a Claim Name and a
>      Claim Value.
>
>   Claim Name
>      The name portion of a claim representation.  A Claim Name is
>      always a string.
>
>   Claim Value
>      The value portion of a claim representation.  A Claim Value can be
>      any JSON value.

This is a valid use case, and you're also allowing Auth0 users to generate claims with nested objects. Please merge the pull request.

**Comment by lbalmaceda** [comment]
Auth0 doesn't restrict what a user can put inside a token, correct. But this SDK still doesn't support obtaining a nested object. We have filled this as a feature-request and will revisit when prioritized by the product team.

**Comment by LiYing2010** [comment]
I already made a PR for this, more than 1 year ago   😥
https://github.com/auth0/JWTDecode.Android/issues/21#issuecomment-396807133

please take a look

**Comment by lbalmaceda** [comment]
I'd have preferred an extensible interface that users can implement themselves to resolve custom deserializations. If we just try `gson.fromJson` and pass a class type I'm afraid we could not guarantee the expected conversion in every scenario. (Can't think of an example now).

That said, I think this has been opened for a long time already and doesn't make sense for us to keep delaying the feature even if we already have it in our backlog.. just that priorities right now in the team do not align with this.

I left a review for `PR 41` and hopefully we can get it merged/released soon. Will close any other related PRs.

Thanks for your patience.

**Comment by lbalmaceda** [comment]
Will be available in `1.4.0`.

**Comment by tsal** [comment]
> Will be available in `1.4.0`.

Any chance we could get the examples updated to include this?
