### ISSUE TITLE
How to verify a token on Android

### ISSUE THREAD

**Issue by mtsahakis** [auth0/JWTDecode.Android#23]
Hi,

In https://github.com/auth0/java-jwt there is a specific section on how to verify a token.

I was wondering if that is possible on the Android side, i.e. if I have the public key and the algorithm, how could we verify that the received token was issued by a valid issuer?

In short, is there any way to verify the issuer of a signed token?

Many thanks in advance,

Manos

**Comment by lbalmaceda** [comment]
@mtsahakis no. This library only performs a **decode** operation without verifying the token's signature. We plan to include this in a near future supporting only RS256 algorithms.

**Comment by ManjunathaKC** [comment]
Any Updates on this implementation? Token verification for the RSA256 algorithm.

**Comment by lbalmaceda** [comment]
👋 @ManjunathaKC the focus of this project is still decoding JWTs. If you happen to be using our Android SDK with an Auth0 client, we have you covered as the SDK is performing OIDC compliant ID token validation before the token gets to you.
