### ISSUE TITLE
Issue: Getting claim values list

### ISSUE THREAD

**Issue by legd** [auth0/JWTDecode.Android#26]
Hi, I’m currently using the library in my android app for receiving a token with a claim called “user_claim” that contains a list of parameters, the decode works fine because I can see the values while debugging but when I use one of the methods asList, asArray, asString to get values of the claim, returns null or an empty list or array, I’m using Java 8 in Android Studio 3.0.1 and jwtdecode:1.1.1, I’m not sure if something is missing, also here is a fragment of my code in case something is missing in my implementation you can tell me:

`JWT jwtToken = new JWT(token);`
`Claim userClaim = jwtToken.getClaim("user_claims");`
`ArrayList<String> list = new ArrayList<>(userClaim.asList(String.class));`

Best
Luis

**Comment by lbalmaceda** [comment]
@legd that's weird.. that case is tested [here](https://github.com/auth0/JWTDecode.Android/blob/master/lib/src/test/java/com/auth0/android/jwt/ClaimImplTest.java#L193-L198). Can you share a token? feel free to remove the signature.

**Comment by legd** [comment]
Here is a token without the signature: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzIzNTEzMjYsIm5iZiI6MTUzMjM1MTMyNiwianRpIjoiYThjMDQzYWUtZmZjZC00MTYyLTlmZjctNzc5NjcxYjU4Yzg3IiwiZXhwIjoxNTMyMzUyMjI2LCJzdWIiOjIyOSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiZGV2aWNlX2lkIjoiMWE3YzBiMzEtZjViOC00OWJlLTgzZjAtZWZhZTcyMjczZDhkIiwidXNlcl90eXBlX2lkIjoxLCJpc190cmlhbCI6dHJ1ZX19

**Comment by lbalmaceda** [comment]
That's not an array/list, it's a map/dictionary structure. This library doesn't support _nested objects_ as of today. We might add it in the future. Follow the related thread here https://github.com/auth0/JWTDecode.Android/issues/21

**Comment by fllaryora** [comment]
Hi lbalmaceda, 
 Does this library support nested objects ? If not
Which library recommend Auth0 to work with?

Thanks in advance!
