### ISSUE TITLE
Urgent :: Not Getting Decode JWT to Json

### ISSUE THREAD

**Issue by kushanshah11** [auth0/JWTDecode.Android#34]
### Description

I m decoding token to json but i m not getting it.

### Environment

Please provide the following:

- Version of JWTDecode.Android used: latest
- Version of Android used:8.0
- Additional libraries that might be affecting your instance:

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Please include:

Token :: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlFqZEdORGcyUlRVM01EYzNPVFpGTVVJNU5EZzRPVFEwUXpoRk5VSXdRek14TURBM1JqQTJNZyJ9.eyJodHRwczovL2NvaGVzaW9uaWIuY29tL2licF9idWlsZGluZ0NvZGUiOiJKSVJBMDAxIiwiaHR0cHM6Ly9jb2hlc2lvbmliLmNvbS9pYnBfY29tcGFueUNvZGUiOiJBMTA1IiwiaHR0cHM6Ly9jb2hlc2lvbmliLmNvbS9pYnBfdXNlcklkIjoiYjMwMjM2MjMtZWFjNi00ZDE5LTgyZWUtMDhkNjhiMzk4OWJhIiwiaHR0cHM6Ly9jb2hlc2lvbmliLmNvbS9pYnBfcm9sZXMiOlt7Im1JZCI6MSwidmFsIjowLCJmTGlzdCI6W3siZklkIjoxMDUsInZhbCI6MH0seyJmSWQiOjEwNCwidmFsIjowfV19LHsibUlkIjoyLCJ2YWwiOjAsImZMaXN0IjpbeyJmSWQiOjIwMiwidmFsIjowfSx7ImZJZCI6MjAzLCJ2YWwiOjB9LHsiZklkIjoyMDEsInZhbCI6MH0seyJmSWQiOjIwNCwidmFsIjowfV19LHsibUlkIjozLCJ2YWwiOjAsImZMaXN0IjpbeyJmSWQiOjMwMSwidmFsIjowfSx7ImZJZCI6MzA0LCJ2YWwiOjB9LHsiZklkIjozMDIsInZhbCI6MH0seyJmSWQiOjMwMywidmFsIjowfSx7ImZJZCI6MzA1LCJ2YWwiOjB9XX0seyJtSWQiOjQsInZhbCI6MCwiZkxpc3QiOlt7ImZJZCI6NDAzLCJ2YWwiOjB9LHsiZklkIjo0MDIsInZhbCI6MH0seyJmSWQiOjQwMSwidmFsIjowfV19LHsibUlkIjo1LCJ2YWwiOjAsImZMaXN0IjpbeyJmSWQiOjUwMiwidmFsIjowfSx7ImZJZCI6NTA0LCJ2YWwiOjB9LHsiZklkIjo1MDEsInZhbCI6MH0seyJmSWQiOjUwNSwidmFsIjowfSx7ImZJZCI6NTAzLCJ2YWwiOjB9XX0seyJtSWQiOjYsInZhbCI6MCwiZkxpc3QiOlt7ImZJZCI6NjAxLCJ2YWwiOjB9LHsiZklkIjo2MDMsInZhbCI6MH0seyJmSWQiOjYwMiwidmFsIjowfV19LHsibUlkIjo3LCJ2YWwiOjAsImZMaXN0IjpbeyJmSWQiOjcwMSwidmFsIjowfSx7ImZJZCI6NzAzLCJ2YWwiOjB9LHsiZklkIjo3MDIsInZhbCI6MH1dfSx7Im1JZCI6OCwidmFsIjowLCJmTGlzdCI6W3siZklkIjo4MDEsInZhbCI6MH0seyJmSWQiOjgwMiwidmFsIjowfV19LHsibUlkIjo5LCJ2YWwiOjAsImZMaXN0IjpbeyJmSWQiOjkwMywidmFsIjowfSx7ImZJZCI6OTAxLCJ2YWwiOjB9LHsiZklkIjo5MDIsInZhbCI6MH0seyJmSWQiOjkwNCwidmFsIjowfV19XSwiaXNzIjoiaHR0cHM6Ly9jb2hlc2lvbmliLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1YzU5MzdjN2ZlMjkxMzA3ZjU1MjEzZDAiLCJhdWQiOlsiaHR0cDovLzEwNC4yMTEuMTY3LjY0OjgyLyIsImh0dHBzOi8vY29oZXNpb25pYi5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNTQ5MzU2NDUxLCJleHAiOjE1NDk0NDI4NTEsImF6cCI6IjRXRTB0OUhsUEpKeTUzN3F1bXEzaU9oRWNuTkJ5MHR0Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBvZmZsaW5lX2FjY2VzcyJ9.dAtyCS2C_OdvvUHRwMEISOC_jUS4xtfX69wR_o8_yvBa5iCoitayb9LMcmAtYc6O62dd97lPQhRVbvD0fljpxqjQ3F8Bqk28wrMlJOB7aqSJuugQWE7t-jAKU5yrgOxrPw9HRQ6kiLQpzqAsd9fsoR_bsESb4e8tG1qhvnI6Ign0a3xOMsAmyYr7Pf2wJWbh_H10ibwUD50q-75npC9P88mOv1vZnga0vpW0OqXy3ZaKUGry4dKwhbsHSfm4JsctneewvdVGT2Ky1Hddlvol6t7pENGY1toaAJN_OY57uo-8J4cb7p0WFH84bAN_A0xAQcYmFI1Nc5Aw_115PEq1KA

  try {
                       JWT jwt = new JWT(payload.getAccessToken());

                       Map<String, Claim> allClaims = jwt.getClaims();

                       Claim subscriptionMetaData =  jwt.getClaim("https: //cohesionib.com/ibp_companyCode");
                       String parsedValue = subscriptionMetaData.asString();

                       Log.e("decoded" ,"" +  parsedValue);
                       Log.e("decoded 1 " ,"" +  allClaims);

                   } catch (DecodeException exception){
                       //Invalid token
                       Log.e("decoded" ,"" +  exception.getMessage());
                   }

All Claim :: {https://cohesionib.com/ibp_companyCode=com.auth0.android.jwt.ClaimImpl@7435f82, sub=com.auth0.android.jwt.ClaimImpl@f557693, aud=com.auth0.android.jwt.ClaimImpl@a3676d0, https://cohesionib.com/ibp_roles=com.auth0.android.jwt.ClaimImpl@64426c9, azp=com.auth0.android.jwt.ClaimImpl@74bf1ce, scope=com.auth0.android.jwt.ClaimImpl@256e8ef, https://cohesionib.com/ibp_buildingCode=com.auth0.android.jwt.ClaimImpl@1d42ffc, iss=com.auth0.android.jwt.ClaimImpl@6df6685, https://cohesionib.com/ibp_userId=com.auth0.android.jwt.ClaimImpl@e395cda, exp=com.auth0.android.jwt.ClaimImpl@353250b, iat=com.auth0.android.jwt.ClaimImpl@1324fe8}

PArticular Claim :: null

Please Help as soon as possible.

**Comment by lbalmaceda** [comment]
👋 Happy to assist you but please complete the template first or delete any irrelevant stuff. 
You're pasting a (still valid) token and a snippet but there are no exceptions or message, so I don't understand what problem is that you're having. **Is there an exception you forgot to share?** 
At a first glance I see you have a typo on the `getClaim()` claim name. If the claim doesn't exist, remember you will always get a valid Claim instance when you call that method as it says in the [method javadoc](https://github.com/auth0/JWTDecode.Android/blob/master/lib/src/main/java/com/auth0/android/jwt/JWT.java#L135-L139).

🛑 I recommend you rotate your keys since you've disclosure the token and be more careful the next time.

**Comment by kushanshah11** [comment]
HI @lbalmaceda 
Thanks for fast response 

Here is accessToken and i want to decode in particular format but i m not able to decode 

token :: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlFqZEdORGcyUlRVM01EYzNPVFpGTVVJNU5EZzRPVFEwUXpoRk5VSXdRek14TURBM1JqQTJNZyJ9.eyJodHRwczovL2NvaGVzaW9uaWIuY29tL2licF9idWlsZGluZ0NvZGUiOiJKSVJBMDAxIiwiaHR0cHM6Ly9jb2hlc2lvbmliLmNvbS9pYnBfdXNlcklkIjoiYjMwMjM2MjMtZWFjNi00ZDE5LTgyZWUtMDhkNjhiMzk4OWJhIiwiaHR0cHM6Ly9jb2hlc2lvbmliLmNvbS9pYnBfcm9sZXMiOnsicm9sZXMiOlt7Im1JZCI6MSwidmFsIjowLCJmTGlzdCI6W3siZklkIjoxMDUsInZhbCI6MH0seyJmSWQiOjEwNCwidmFsIjowfV19LHsibUlkIjoyLCJ2YWwiOjAsImZMaXN0IjpbeyJmSWQiOjIwMiwidmFsIjowfSx7ImZJZCI6MjAzLCJ2YWwiOjB9LHsiZklkIjoyMDEsInZhbCI6MH0seyJmSWQiOjIwNCwidmFsIjowfV19LHsibUlkIjozLCJ2YWwiOjAsImZMaXN0IjpbeyJmSWQiOjMwMSwidmFsIjowfSx7ImZJZCI6MzA0LCJ2YWwiOjB9LHsiZklkIjozMDIsInZhbCI6MH0seyJmSWQiOjMwMywidmFsIjowfSx7ImZJZCI6MzA1LCJ2YWwiOjB9XX0seyJtSWQiOjQsInZhbCI6MCwiZkxpc3QiOlt7ImZJZCI6NDAzLCJ2YWwiOjB9LHsiZklkIjo0MDIsInZhbCI6MH0seyJmSWQiOjQwMSwidmFsIjowfV19LHsibUlkIjo1LCJ2YWwiOjAsImZMaXN0IjpbeyJmSWQiOjUwMiwidmFsIjowfSx7ImZJZCI6NTA0LCJ2YWwiOjB9LHsiZklkIjo1MDEsInZhbCI6MH0seyJmSWQiOjUwNSwidmFsIjowfSx7ImZJZCI6NTAzLCJ2YWwiOjB9XX0seyJtSWQiOjYsInZhbCI6MCwiZkxpc3QiOlt7ImZJZCI6NjAxLCJ2YWwiOjB9LHsiZklkIjo2MDMsInZhbCI6MH0seyJmSWQiOjYwMiwidmFsIjowfV19LHsibUlkIjo3LCJ2YWwiOjAsImZMaXN0IjpbeyJmSWQiOjcwMSwidmFsIjowfSx7ImZJZCI6NzAzLCJ2YWwiOjB9LHsiZklkIjo3MDIsInZhbCI6MH1dfSx7Im1JZCI6OCwidmFsIjowLCJmTGlzdCI6W3siZklkIjo4MDEsInZhbCI6MH0seyJmSWQiOjgwMiwidmFsIjowfV19LHsibUlkIjo5LCJ2YWwiOjAsImZMaXN0IjpbeyJmSWQiOjkwMywidmFsIjowfSx7ImZJZCI6OTAxLCJ2YWwiOjB9LHsiZklkIjo5MDIsInZhbCI6MH0seyJmSWQiOjkwNCwidmFsIjowfV19XX0sImlzcyI6Imh0dHBzOi8vY29oZXNpb25pYi5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWM1OTM3YzdmZTI5MTMwN2Y1NTIxM2QwIiwiYXVkIjpbImh0dHA6Ly8xMDQuMjExLjE2Ny42NDo4Mi8iLCJodHRwczovL2NvaGVzaW9uaWIuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU0OTQzMDE1MCwiZXhwIjoxNTQ5NTE2NTUwLCJhenAiOiI0V0UwdDlIbFBKSnk1MzdxdW1xM2lPaEVjbk5CeTB0dCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MifQ.l-oLbEbbZSgr0wFYjZ_ZLdjgonmyFVOqIq1zjJ7pHcrxn4rNFmONS3yK84_jKPB2LgJIYQ-Zc3K4IjjAn4zdbBLUtI9M0vVSNCY-72jm17qBtJ-gXf46MNGuUAsovygQKFMoGX13MAGmeq5b_QYHApnujuenljhw8DvLqgidbz7YQoOtL-MPIz1-dfV2T-kQnUps7T51B1Zz8vsr6ZnvryML1rTmQgIWphHonaduA6DJEE0GoE8Tdn0VSG2akWmtZwjiVbpXse6EbJtblTZIc7_rc725SVnSdgj4bWhaZyTac6qmD2LOX6Wzs9CuksSmhlt6e8ObjQG2Z-fBZdwWIQ

Actual Result what i want :: {
  "https://cohesionib.com/ibp_buildingCode": "JIRA001",
  "https://cohesionib.com/ibp_userId": "b3023623-eac6-4d19-82ee-08d68b3989ba",
  "https://cohesionib.com/ibp_roles": {
    "roles": [
      {
        "mId": 1,
        "val": 0,
        "fList": [
          {
            "fId": 105,
            "val": 0
          },
          {
            "fId": 104,
            "val": 0
          }
        ]
      },
      {
        "mId": 2,
        "val": 0,
        "fList": [
          {
            "fId": 202,
            "val": 0
          },
          {
            "fId": 203,
            "val": 0
          },
          {
            "fId": 201,
            "val": 0
          },
          {
            "fId": 204,
            "val": 0
          }
        ]
      },
      {
        "mId": 3,
        "val": 0,
        "fList": [
          {
            "fId": 301,
            "val": 0
          },
          {
            "fId": 304,
            "val": 0
          },
          {
            "fId": 302,
            "val": 0
          },
          {
            "fId": 303,
            "val": 0
          },
          {
            "fId": 305,
            "val": 0
          }
        ]
      },
      {
        "mId": 4,
        "val": 0,
        "fList": [
          {
            "fId": 403,
            "val": 0
          },
          {
            "fId": 402,
            "val": 0
          },
          {
            "fId": 401,
            "val": 0
          }
        ]
      },
      {
        "mId": 5,
        "val": 0,
        "fList": [
          {
            "fId": 502,
            "val": 0
          },
          {
            "fId": 504,
            "val": 0
          },
          {
            "fId": 501,
            "val": 0
          },
          {
            "fId": 505,
            "val": 0
          },
          {
            "fId": 503,
            "val": 0
          }
        ]
      },
      {
        "mId": 6,
        "val": 0,
        "fList": [
          {
            "fId": 601,
            "val": 0
          },
          {
            "fId": 603,
            "val": 0
          },
          {
            "fId": 602,
            "val": 0
          }
        ]
      },
      {
        "mId": 7,
        "val": 0,
        "fList": [
          {
            "fId": 701,
            "val": 0
          },
          {
            "fId": 703,
            "val": 0
          },
          {
            "fId": 702,
            "val": 0
          }
        ]
      },
      {
        "mId": 8,
        "val": 0,
        "fList": [
          {
            "fId": 801,
            "val": 0
          },
          {
            "fId": 802,
            "val": 0
          }
        ]
      },
      {
        "mId": 9,
        "val": 0,
        "fList": [
          {
            "fId": 903,
            "val": 0
          },
          {
            "fId": 901,
            "val": 0
          },
          {
            "fId": 902,
            "val": 0
          },
          {
            "fId": 904,
            "val": 0
          }
        ]
      }
    ]
  },
  "iss": "https://cohesionib.auth0.com/",
  "sub": "auth0|5c5937c7fe291307f55213d0",
  "aud": [
    "http://104.211.167.64:82/",
    "https://cohesionib.auth0.com/userinfo"
  ],
  "iat": 1549430150,
  "exp": 1549516550,
  "azp": "4WE0t9HlPJJy537qumq3iOhEcnNBy0tt",
  "scope": "openid profile email offline_access"
}

Please help me out this.

Thanks.

**Comment by lbalmaceda** [comment]
No, this is not currently supported. For the time being we only support plain (1 level) payload structures. I'll close this issue but you can track that feature request [here](https://github.com/auth0/JWTDecode.Android/issues/34).
