### ISSUE TITLE
getClaim return null

### ISSUE THREAD

**Issue by felixeduardo15** [auth0/JWTDecode.Android#40]
Hi maintainers anyone can help me. We use the next token, but when use getClaim function the value return is null. We use a debugger to explain what happens, it has a full payload, but return null after getAsString.

`String token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkU2VydmljZXMiOlsiYXBpLXVzdWFyaW9zLTEyM3Bvcm1pIiwiYmVuZWZpY2lvcyJdLCJwYXlsb2FkIjp7ImlkIjoyMSwibmFtZSI6IkJyZW5kYSIsImZpcnN0U3VybmFtZSI6IkRvbcOtbmd1ZXoiLCJzZWNvbmRTdXJuYW1lIjoiR8OhbWV6IiwiZW1wbG95ZWVJZCI6MzEyNX0sImlhdCI6MTU2ODg1MjIwNywiZXhwIjoxNTY4ODUyODA3fQ.VCvXEAXWUheHd4JCp-QxRr0AADn_akQGMAsok4WY19Jo74LdFYpgx7N-fBs4qGlJ3cIurUkyUOOCc8F_XXjdt5qTOx2Y2GHYgsrOD5Jwx9ZJ-F7GBmq1aY6ubRDBCTKnlJnunIsF-r4Cdp1qJy6Ygaag_G8fWGYdGNFS4De53tm8WMTi2IFeO_AitRSJbrqG8YWyFe1T4UQXTuv8NTJ9WkZFbcQwJMtYAGbltY5FxhFL3ReL7dVGb-rxMCnBEFs-IPOu4Or6K0vOaXXaxl7TRJV2OU2Xh1ulLbosG09Wce0jHn18Rw22K1wanF71H1nv8bwmJsQB5meWykevRi3T3g";`

```
JWT jwt = new JWT(token);
String name = jwt.getClaim("name").asString();
```

**Comment by lbalmaceda** [comment]
@felixeduardo15 As you see [here](https://jwt.io/?value=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkU2VydmljZXMiOlsiYXBpLXVzdWFyaW9zLTEyM3Bvcm1pIiwiYmVuZWZpY2lvcyJdLCJwYXlsb2FkIjp7ImlkIjoyMSwibmFtZSI6IkJyZW5kYSIsImZpcnN0U3VybmFtZSI6IkRvbcOtbmd1ZXoiLCJzZWNvbmRTdXJuYW1lIjoiR8OhbWV6IiwiZW1wbG95ZWVJZCI6MzEyNX0sImlhdCI6MTU2ODg1MjIwNywiZXhwIjoxNTY4ODUyODA3fQ.VCvXEAXWUheHd4JCp-QxRr0AADn_akQGMAsok4WY19Jo74LdFYpgx7N-fBs4qGlJ3cIurUkyUOOCc8F_XXjdt5qTOx2Y2GHYgsrOD5Jwx9ZJ-F7GBmq1aY6ubRDBCTKnlJnunIsF-r4Cdp1qJy6Ygaag_G8fWGYdGNFS4De53tm8WMTi2IFeO_AitRSJbrqG8YWyFe1T4UQXTuv8NTJ9WkZFbcQwJMtYAGbltY5FxhFL3ReL7dVGb-rxMCnBEFs-IPOu4Or6K0vOaXXaxl7TRJV2OU2Xh1ulLbosG09Wce0jHn18Rw22K1wanF71H1nv8bwmJsQB5meWykevRi3T3g) ![image](https://user-images.githubusercontent.com/3900123/67512705-ca755280-f66f-11e9-9ccf-c2a54d7f4c70.png)

The "name" attribute is inside the claim "payload". You'd need to first obtain the "payload" claim and then obtain the "name" attribute. 

Note there's no current support for nested JSON objects yet (more on #21). If you need that today and you can change the token structure, is encouraged that you make the structure plain.
