### ISSUE TITLE
Pro-guard Issue

### ISSUE THREAD

**Issue by Srj-Love** [auth0/JWTDecode.Android#49]
I'm not able to extract data when I enable minifyEnabled true in release build, instead it's working perfectly in debug mode.

**Comment by gadregit** [comment]
I am also facing the same issue, the moment i turn on minifyEnabled true in my build gradle for different build type it crashes right upon login. Are there any proguard rules that we need to follow when adding this library?

**Comment by emartynov** [comment]
I believe this is due to usage of GSON.

**Comment by emartynov** [comment]
I need help or some rubber ducking. The library works in debug. However, has issue when obfuscated.

Here is the code:
```
                        Timber.d("JWT ${jwtValue}")
                        val jwtToken = JWT(jwtValue)
                        val claim = jwtToken.claims["e"]
                        Timber.d("JSON ${claim!!.asString()}")
```

It doesn't produce any exception. I see output:

```
JWT eyJ0eXAiOiJ.....
JSON null
```

I have rules for GSON added. Any ideas what can go wrong?

**Comment by Wewe12** [comment]
@emartynov are you sure that you used the latest Gson proguard rules? Check if you have this rule:
```
# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken
```
I had similar problem and resolved them in this way

**Comment by emartynov** [comment]
Oke, to update you about our issue - we are getting our class data serialized in the JWT. So problem was that we obfuscated own class and since our project don't use GSON annotations that was not possible to deserialize.

**Comment by spacemase** [comment]
proguard rules should be supplied by JWT.decode.  The directives above should be added to this `consumerProguardFiles` file, so everyone's projects work and the necessary directives are visible to consumers.
