### ISSUE TITLE
Nullpointer Exception - base64decode()

### ISSUE THREAD

**Issue by trmi1012** [auth0/JWTDecode.Android#51]
### Description

Getting Nullpointer Exception after calling:

`val token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"`
 
`val jwt = JWT(token)`

This line returns null for string: `"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"`
`byte[] bytes = Base64.decode(string, Base64.URL_SAFE | Base64.NO_WRAP | Base64.NO_PADDING);`

In Gradle:
    `implementation 'com.auth0.android:jwtdecode:2.0.0'`

Stacktrace:

> java.lang.NullPointerException
> 	at java.lang.String.<init>(String.java:515)
> 	at com.auth0.android.jwt.JWT.base64Decode(JWT.java:235)
> 	at com.auth0.android.jwt.JWT.decode(JWT.java:213)
> 	at com.auth0.android.jwt.JWT.<init>(JWT.java:40)
> 	at *.utils.TokenValidator.isTokenValid(TokenValidator.kt:9)
> 	at *.pwa.webview.PWAWebViewModelImpl$onTokenInvalid$1.invoke(PWAWebViewModel.kt:273)
> 	at *.pwa.webview.PWAWebViewModelImpl$onTokenInvalid$1.invoke(PWAWebViewModel.kt:48)
> 	at *.utils.TestPWAModel.onTokenInvalid(MockFactory.kt:218)
> 	at *.webview.PWAWebViewModelImpl.onTokenInvalid(PWAWebViewModel.kt:272)
> 	at *.PWAWebViewModelTest.new token is passed in token invalid callback(PWAWebViewModelTest.kt:426)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:44)
> 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:74)
> 	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:80)
> 	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
> 	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

**Comment by RowanG1Bilue** [comment]
I have the same issue. Any resolution?

**Comment by lbalmaceda** [comment]
@trmi1012 as @RowanG1Bilue kindly pointed out, there are classes that are only available on an android device. `Base64` in this case is the [android](https://developer.android.com/reference/android/util/Base64) one and needs to be mocked if you intend to use it from the tests. Frameworks like [Robolectric](http://robolectric.org/) help you write android tests by mocking these for you automatically.

**Comment by PushparajLidavi** [comment]
@RunWith(RobolectricTestRunner::class)
class LoginViewModelTest {
}

adding "@RunWith(RobolectricTestRunner::class)" solved this
