### ISSUE TITLE
When minifyEnabled is set to true, android app crashes moment user logs in. Using different build type than release.

### ISSUE THREAD

**Issue by gadregit** [auth0/JWTDecode.Android#56]
When minifyEnabled is set to true, android app crashes moment user logs in and receives JWT token.
Do we need to add any proguard rules while using this library? Nothing is mentioned in steps so i was wondering.
### What was the expected behavior?

User should be able to login with valid token received from server. If i remove minifyEnabled flag it works.

- Version of the library used : 2.0.0
- Crash log:
g.b.a.a.d: The token was expected to have 3 parts, but got 1.
        at g.b.a.a.e.<init>(:6)
        at g.c.a.a.k.b.a(Unknown Source:7)
        at g.c.a.a.i.j.a(:11)
        at g.c.a.a.j.a$b.a(Unknown Source:12)
        at j.l0.g.e$a.run(:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by lbalmaceda** [comment]
> User should be able to login with valid token received from server. 

Apologies for the late response. Note this library is not for logging in, but only for decoding a token and obtaining its claims. If you can share some code with the usage we can help you further.

"The token was expected to have 3 parts, but got 1." gives us the hint that the token is not a well-formed JWT. So my first question would be what value are you passing?

**Comment by rocboronat** [comment]
@gadregit maybe you are parsing any of the JWT values using a class that Proguard is obfuscating?
