### ISSUE TITLE
Exception thrown when json field null

### ISSUE THREAD

**Issue by gjsalot** [auth0/JWTDecode.Android#57]
### Describe the problem

An exception is thrown when parsing a JWT with explicit nulls instead of absent fields.

### What was the expected behavior?

The JWT token is parsed with null fields

### Reproduction

Try parsing

```
eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOm51bGx9.2zjeZFRPs4sTM9Lmb10uzLOJdWAtlmGUQJByV8o8jZY
```

this corresponds to:

```
{
  "iss": null
}
```

an exception will be thrown, whereas one would not be thrown with:

```
{}
```

This exception comes from calling `.getAsString()` on JsonNull in this method https://github.com/auth0/JWTDecode.Android/blob/master/lib/src/main/java/com/auth0/android/jwt/JWTDeserializer.java#L71.

Perhaps you could change your check to:

```
if (!obj.has(claimName) || obj.get(claimName).isJsonNull()) {
    return null;
}
```

**Comment by lbalmaceda** [comment]
I'm not a big fan of nulls but I know it's valid JSON. I think the solution you proposed is correct. Do you want to send a PR for us to review? If you do, make sure to add the unit test.
