### ISSUE TITLE
jwt.getClaims().get("referCode").asString() returns null even if present

### ISSUE THREAD

**Issue by vaibhavmandlik** [auth0/JWTDecode.Android#70]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/JWTDecode.Android#readme) and [Examples](https://github.com/auth0/JWTDecode.Android/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/jwtdecode/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/JWTDecode.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, can anyone help me with this? I'm trying to extract the data from the JWT token using JWTDecode. When I debug, I get the values but when I use them I get null.

### Reproduction

``String token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZhaWJoYXYubWFuZGxpazFAZ21haWwuY29tIiwiaWQiOjEsImNhdGVnb3J5IjoiMSIsImVtYWlsIjoidmFpYmhhdi5tYW5kbGlrMkBnbWFpbC5jb20iLCJyZWZlckNvZGUiOiJWVFlKSCIsImlhdCI6MTY4NTg3MTkxNSwiZXhwIjoxNjg1ODc1NTE1fQ.XPKYs9mhS3pgF13a5PDek0EhM_izfg1gP0aCxyxdWAI";``

`     JSONObject jsonObject = new JSONObject(userData);
      JWT jwt = new JWT(jsonObject.getString("token"));
     if (jwt.getClaims().containsKey("referCode")) {
          TextView referCode = dialog.findViewById(R.id.refer_code);
          referCode.setText(jwt.getClaims().get("referCode").asString());
   }
`

### JWTDecode.Android version

2.0.2

### Android version(s)

13

**Comment by poovamraj** [comment]
Hi @vaibhavmandlik are you sure about this? I used the same JWT and ran a test and it seems to work fine. 

```
@Test
public void shouldTestIssue() {
    JWT jwt = new JWT("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZhaWJoYXYubWFuZGxpazFAZ21haWwuY29tIiwiaWQiOjEsImNhdGVnb3J5IjoiMSIsImVtYWlsIjoidmFpYmhhdi5tYW5kbGlrMkBnbWFpbC5jb20iLCJyZWZlckNvZGUiOiJWVFlKSCIsImlhdCI6MTY4NTg3MTkxNSwiZXhwIjoxNjg1ODc1NTE1fQ.XPKYs9mhS3pgF13a5PDek0EhM_izfg1gP0aCxyxdWAI");
    assertThat(jwt, is(notNullValue()));
    System.out.println(jwt.getClaims().get("referCode").asString());
    assertThat(jwt.getClaims().get("referCode").asString(), is("VTYJH"));
}
```
