### ISSUE TITLE
com.auth0.android.jwt.DecodeException: The token was expected to have 3 parts, but got 1.

### ISSUE THREAD

**Issue by pavelsust** [auth0/JWTDecode.Android#71]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/JWTDecode.Android#readme) and [Examples](https://github.com/auth0/JWTDecode.Android/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/jwtdecode/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/JWTDecode.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,

Recently I found this issue. Sometimes it shows this error but If i decode error token in jwt website it is ok. can you please look into it

com.auth0.android.jwt.DecodeException: The token was expected to have 3 parts, but got 1.

### Reproduction

1. use token to decode.

### JWTDecode.Android version

2.0.2

### Android version(s)

12

**Comment by poovamraj** [comment]
@pavelsust Can you provide us with a sample token here so that we can try to reproduce it? The error you mentioned happens if there are not 3 parts to the JWT token. Can you also share the screenshot from jwt.io?

**Comment by poovamraj** [comment]
@pavelsust we will close this issue. Feel free to comment here and we can reopen it if required.
